[default]
locale = "en-ca"

[default.extend-words]
monolog = "monolog"
Monolog = "Monolog"

[files]
extend-exclude = [
    "/public/vendor/",
    "/public/robots.txt",
    "/package-lock.json",
    "/sonar-project.properties",
    "/artisan",
    "/pint.json",
    "/rector.php",
    "/phpunit.xml",
    "/composer.lock",
    "*.min.*",
    ".gitignore",
    "/storage/app/blocklists/",
]
